language: ruby
rvm:
- 2.0.0

script: rake travis

deploy:
  provider: heroku
  api_key:
    secure: ZhopNkxXSY9U6emx9M64zm9o1OrCQTXscHxhtG+IIHkucQFnf/RzGkTPtBiuOj46kVNXQ4UiYM2qnPYdzH+ufjk764fFHOcVc0VaoNzZkgFdGaLk5dwhvwoaZ1zhARDGCYpgs5TwQCPHST1MPxVyLo4lYQAlkHixlKGwJfisIoQ=
  app: goodthing
  on:
    repo: jleo3/gtr

notifications:
  email:
    on_success: always
